### ISSUE TITLE
Swap ctrl + wheel ctrl + shift + wheel 

### ISSUE THREAD

**Issue by eprst5000** [lokanchung/StudioPlusOne#1]
Hi, the swap feature does not work for me, unfortunately.
Win 10, 64bit

**Comment by lokanchung** [comment]
Coudn't reproduce it. Which version of S1 are you using? Also try running the utility with admin privilege

**Comment by eprst5000** [comment]
Hi, strange.  _S1 Pro 5.4.1 - Win 10 21H1 - AHK 1.1.33.10_

I start the sp1.ahk as admin. MMB drag to pan around works perfectly. ctrl + wheel = change track height. ctrl + shift + wheel = zoom horizontally

I have another .ahk file that only contains the "swap" function, and it works when I run it.

No matter how this turns out, thank you for your attention!

**Comment by lokanchung** [comment]
Hmm it could be related to configuration then. You turned it on from the settings (right click tray icon to open it) and still swap function isn't working right? It's off by default for those who don't want swap feature.

**Comment by eprst5000** [comment]
omg, I am very very sorry about that. I didn't know there was a settings menu. It works now and so perfectly! I am very grateful to you!

THANK YOU!

**Comment by lokanchung** [comment]
Sounds great! Maybe I should update that in the readme. Sorry for late response and thanks for using my extension! Have a good day!
