### ISSUE TITLE
MMB panning and mousewheel bindings don't work when using studio one on a secondary monitor

### ISSUE THREAD

**Issue by ericzyhan** [lokanchung/StudioPlusOne#4]
how to reproduce:
- drag main studio one window to secondary monitor

**Comment by MintyDoggo** [comment]
I couldn't reproduce this issue. Is it still happening and if so could you attach a video of the problem?

**Comment by MintyDoggo** [comment]
Was able to reproduce this issue. This only happens when the primary monitor is not on the very left. As a temporary fix, you can change your primary monitor to be on the very left.

**Comment by lokanchung** [comment]
Sorry I completely forgot about this because I don't have multiple monitors.
Thanks for looking into this, do you have any ideas for fix?

**Comment by MintyDoggo** [comment]
😮
